project:
  type: website
  output-dir: docs

website:
  title: "MEMELAND"

  page-footer:
    left: "&copy; Copyright 2025, MEMELAND"
    right: "This page is built by Ondřej Mottl with ❤️ and [Quarto](https://quarto.org/)."

  site-url: https://memeland-erc.github.io
  repo-url: https://github.com/MEMELAND-ERC/MEMELAND-ERC.github.io
  issue-url: https://github.com/MEMELAND-ERC/MEMELAND-ERC.github.io/issues
  repo-actions: source

  image: Materials/Logos/MEMELAND.png
  favicon: Materials/Logos/MEMELAND.png

  page-navigation: true
  back-to-top-navigation: true

  navbar:
    title: MEMELAND
    search: true
    tools:
      - icon: github
        href: https://github.com/MEMELAND-ERC/MEMELAND-ERC.github.io
    left:
      - text: About
        href: about.qmd

      - text: Team
        href: team.qmd

      - text: Contact
        href: join_us.qmd

format:
  html:
    theme:
      - custom_style.scss
    toc: false
